name: BC Test

on:
  workflow_dispatch:
  push:
  merge_group:

env:
  IMAGE_REPOSITORY: "us-east1-docker.pkg.dev/the-coral-project/coral/talk"
  IMAGE_CACHE_REPOSITORY: "coralproject/ci"
  DOCKERHUB_USERNAME: "coralproject"

jobs:
  bc-test:
    name: bc-test
    runs-on: coral-ci-arm
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: the-coral-project
          workload_identity_provider: projects/418768622481/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@the-coral-project.iam.gserviceaccount.com
